language: swift
jobs:  
  include:
    - stage: test
      name: iOS
      osx_image: xcode12.5
      script:
        - xcodebuild clean test -project SwiftDraw.xcodeproj -scheme SwiftDraw -sdk iphonesimulator14.5 -destination "name=iPhone 12 Pro"
    - stage: test
      name: macOS
      osx_image: xcode12.5
      script:
        - xcodebuild clean test -project SwiftDraw.xcodeproj -scheme SwiftDraw-macOS -sdk macosx
      after_success: bash <(curl -s https://codecov.io/bash) -J 'SwiftDraw'
    - stage: test
      name: Swift PM
      osx_image: xcode12.5
      script:
        - swift package clean; swift test
