language: objective-c
osx_image: xcode10.1
jobs:  
  include:
    - stage: test
      name: iOS
      script: xcodebuild clean test -project SwiftDraw.xcodeproj -scheme SwiftDraw -sdk iphonesimulator12.1
    - stage: test
      name: macOS
      script: xcodebuild clean test -project SwiftDraw.xcodeproj -scheme SwiftDraw-macOS -sdk macosx
